import opentype from 'opentype.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
  const fontPath = path.resolve(__dirname, '../fonts/KreativeSquare.ttf');
  const outPath = path.resolve(__dirname, '../src/utils/valid_glyphs.ts');
  
  const font = await opentype.load(fontPath);
  
  const glyphs = font.glyphs;
  const validCodes = new Set();
  
  for (let i = 0; i < glyphs.length; i++) {
    const glyph = glyphs.get(i);
    // glyph.unicode contains the primary codepoint
    // glyph.unicodes contains all codepoints mapped to this glyph
    if (glyph.unicodes.length > 0) {
      glyph.unicodes.forEach(code => validCodes.add(code));
    } else if (glyph.unicode) {
      validCodes.add(glyph.unicode);
    }
  }

  // Sort them so they display nicely in order
  const sortedCodes = Array.from(validCodes).sort((a, b) => a - b);
  
  // Filter out any control chars if we want (e.g. < 0x20)
  const displayable = sortedCodes.filter(c => c >= 0x20);

  const fileContent = `// Auto-generated by scripts/extract_glyphs.js
export const VALID_GLYPHS: number[] = [
  ${displayable.join(',\n  ')}
];
`;

  fs.writeFileSync(outPath, fileContent, 'utf-8');
  console.log(`Extracted ${displayable.length} valid glyph codepoints.`);
}

main().catch(console.error);
