const https = require('https');
const fs = require('fs');
const path = require('path');

const URL = 'https://fonts.google.com/metadata/fonts';
const OUT = path.join(__dirname, '..', 'src', 'data', 'googleFonts.ts');

https.get(URL, (res) => {
    let data = '';
    res.on('data', chunk => data += chunk);
    res.on('end', () => {
        const json = JSON.parse(data.replace(/^\)\]\}'\n/, ''));
        const fonts = json.familyMetadataList.map(f => ({
            family: f.family,
            category: f.category,
            subsets: f.subsets,
            popularity: f.popularity,
        }));

        fonts.sort((a, b) => a.popularity - b.popularity);

        const categories = [...new Set(fonts.map(f => f.category))].sort();

        const lines = [
            '// Auto-generated by scripts/fetch_google_fonts.js',
            `// ${fonts.length} fonts, fetched ${new Date().toISOString().split('T')[0]}`,
            '',
            'export interface GoogleFont {',
            '  family: string;',
            '  category: string;',
            '}',
            '',
            `export const GOOGLE_FONT_CATEGORIES = ${JSON.stringify(categories)} as const;`,
            'export type GoogleFontCategory = typeof GOOGLE_FONT_CATEGORIES[number];',
            '',
            'export const GOOGLE_FONTS: GoogleFont[] = [',
        ];

        for (const f of fonts) {
            lines.push(`  { family: ${JSON.stringify(f.family)}, category: ${JSON.stringify(f.category)} },`);
        }

        lines.push('];');
        lines.push('');

        fs.mkdirSync(path.dirname(OUT), { recursive: true });
        fs.writeFileSync(OUT, lines.join('\n'));
        console.log(`Wrote ${fonts.length} fonts to ${OUT}`);
        console.log(`Categories: ${categories.join(', ')}`);
    });
}).on('error', err => {
    console.error('Failed to fetch:', err.message);
    process.exit(1);
});
